---
name: tag

# ---------------
# Control secrets
# ---------------
#
# At the GitHub 'organisation' or 'project' level you are expected to
# have the following GitHub 'Repository Secrets' defined
# (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# (none)

on:
  push:
    tags:
    - '*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set lower case owner name
      run: echo "owner=${OWNER,,}" >> "$GITHUB_ENV"
      env:
        OWNER: '${{ github.repository_owner }}'
    - name: Set version
      run: echo ${{ github.ref_name }} > VERSION
    - name: Build and Push (Tag)
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.owner }}/fragalysis-mock-target-access-authenticator:${{ github.ref_name }}
        push: true
